# Generated by Django 5.0 on 2024-09-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contactformlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformlog',
            old_name='error_messages',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='contactformlog',
            old_name='is_succes',
            new_name='is_success',
        ),
    ]
