# Generated by Django 5.0 on 2024-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactformlog',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='author',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactformlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
